# Generated by Django 3.0 on 2020-04-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Название вакансии'),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='Название документа')),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Опиписание документа')),
                ('doc_file', models.FileField(upload_to='documents', verbose_name='Загруженный документ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ('title',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
