# Generated by Django 3.0 on 2020-04-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200423_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14, verbose_name='Телефон')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('pub_date', 'name'),
            },
        ),
    ]
